version: "3"
services:
  recalendar.me:
    command: [ "bash", "init.sh" ]
    container_name: recalendar.me
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    hostname: recalendar.me
    image: t00geek/recalendar.me:1.0
    ipc: private
    ports:
      - 3000:3000/tcp
    stdin_open: true
    tty: true
    restart: always
